/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.rezervacija;

import forme.*;
import domen.Korisnik;
import domen.Mesto;
import domen.Rezervacija;
import gui.komponente.TblModelKorisnik;
import gui.komponente.TblModelRezervacija;
import java.awt.Point;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import korisnici.kontroler.Kontroler;
import util.Util;

/**
 *
 * @author Aco Kandic
 */
public class FmPretragaRezervacija extends javax.swing.JDialog {

    /**
     * Creates new form FmPretragaKorisnika
     */
    
    public static List<Korisnik> listaKorisnikaFilter = new ArrayList<>();
    
    public FmPretragaRezervacija(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(jradioBrojRezervacije);
        bg.add(jradioKorisnik);
        bg.add(jradioProstorija);
        bg.add(jradioDatumRezervacije);
        bg.add(jradioVremeOd);
        bg.add(jradioVremeDo);
        jradioBrojRezervacije.setSelected(true);
        
        srediTabelu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_detalji = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRezervacije = new javax.swing.JTable();
        jbtnResetujRezultate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jradioBrojRezervacije = new javax.swing.JRadioButton();
        jradioKorisnik = new javax.swing.JRadioButton();
        jradioProstorija = new javax.swing.JRadioButton();
        jradioDatumRezervacije = new javax.swing.JRadioButton();
        jradioVremeOd = new javax.swing.JRadioButton();
        jradioVremeDo = new javax.swing.JRadioButton();
        jbtnTrazi = new javax.swing.JButton();
        jtxtPretraga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jbtn_detalji.setText("Detalji");
        jbtn_detalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_detaljiActionPerformed(evt);
            }
        });

        jScrollPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jScrollPane1FocusGained(evt);
            }
        });

        jtblRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Broj rezervacije", "Korisnik", "Prostorija", "Datum rezervacije", "Vreme od", "Vreme do", "Iznos"
            }
        ));
        jtblRezervacije.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtblRezervacijeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtblRezervacijeFocusLost(evt);
            }
        });
        jtblRezervacije.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblRezervacijeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblRezervacije);

        jbtnResetujRezultate.setText("Resetuj rezultate");
        jbtnResetujRezultate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetujRezultateActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pretraga rezervacija"));

        jradioBrojRezervacije.setText("Broj rezervacije");
        jradioBrojRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioBrojRezervacijeActionPerformed(evt);
            }
        });

        jradioKorisnik.setText("Korisnik");
        jradioKorisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioKorisnikActionPerformed(evt);
            }
        });

        jradioProstorija.setText("Prostorija");
        jradioProstorija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioProstorijaActionPerformed(evt);
            }
        });

        jradioDatumRezervacije.setText("Datum rezervacije");
        jradioDatumRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioDatumRezervacijeActionPerformed(evt);
            }
        });

        jradioVremeOd.setText("Vreme od");
        jradioVremeOd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioVremeOdActionPerformed(evt);
            }
        });

        jradioVremeDo.setText("Vreme do");
        jradioVremeDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioVremeDoActionPerformed(evt);
            }
        });

        jbtnTrazi.setText("Trazi");
        jbtnTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTraziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jradioBrojRezervacije)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jtxtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jradioKorisnik)
                        .addGap(18, 18, 18)
                        .addComponent(jradioProstorija)
                        .addGap(18, 18, 18)
                        .addComponent(jradioDatumRezervacije)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jbtnTrazi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jradioVremeOd)
                        .addGap(18, 18, 18)
                        .addComponent(jradioVremeDo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradioBrojRezervacije)
                    .addComponent(jradioKorisnik)
                    .addComponent(jradioProstorija)
                    .addComponent(jradioDatumRezervacije)
                    .addComponent(jradioVremeOd)
                    .addComponent(jradioVremeDo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnTrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtPretraga))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtn_detalji, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jbtnResetujRezultate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_detalji)
                    .addComponent(jbtnResetujRezultate))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtblRezervacijeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblRezervacijeMouseClicked
//        int selectedUser = jtblRezervacije.getSelectedRow();
//        jComboKorisnici.setSelectedIndex(selectedUser);
    }//GEN-LAST:event_jtblRezervacijeMouseClicked

    private void jScrollPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jScrollPane1FocusGained
    }//GEN-LAST:event_jScrollPane1FocusGained

    private void jtblRezervacijeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtblRezervacijeFocusGained

    }//GEN-LAST:event_jtblRezervacijeFocusGained

    private void jtblRezervacijeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtblRezervacijeFocusLost
 
    }//GEN-LAST:event_jtblRezervacijeFocusLost

    private void jbtnResetujRezultateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetujRezultateActionPerformed
//        popuniTabeluKorisnici();
//        popuniComboKorisnici();
//        dodajComboMestaUTabelu();
    }//GEN-LAST:event_jbtnResetujRezultateActionPerformed

    private void jbtn_detaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_detaljiActionPerformed
//        Kontroler.vratiInstancuKontrolera().setAktivanSK(Util.SK_IZMENA_KORISNIKA);
//        Korisnik k = (Korisnik) jComboKorisnici.getSelectedItem();
//        Kontroler.vratiInstancuKontrolera().getSesija().put("izabrani_korisnik", k);
//        FmKorisnik fmk = new FmKorisnik(null, true);
//        fmk.setVisible(true);
//        Kontroler.vratiInstancuKontrolera().getSesija().remove("izabrani_korisnik", k);
    }//GEN-LAST:event_jbtn_detaljiActionPerformed

    private void jradioBrojRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioBrojRezervacijeActionPerformed
    }//GEN-LAST:event_jradioBrojRezervacijeActionPerformed

    private void jradioKorisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioKorisnikActionPerformed
    }//GEN-LAST:event_jradioKorisnikActionPerformed

    private void jradioProstorijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioProstorijaActionPerformed
    }//GEN-LAST:event_jradioProstorijaActionPerformed

    private void jradioDatumRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioDatumRezervacijeActionPerformed
    }//GEN-LAST:event_jradioDatumRezervacijeActionPerformed

    private void jradioVremeOdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioVremeOdActionPerformed
    }//GEN-LAST:event_jradioVremeOdActionPerformed

    private void jradioVremeDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioVremeDoActionPerformed
    }//GEN-LAST:event_jradioVremeDoActionPerformed

    private void jbtnTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTraziActionPerformed
        if (jradioBrojRezervacije.isSelected()) {
            JOptionPane.showMessageDialog(this, "Broj rezervacije je pretrazen!");
        }
        if (jradioKorisnik.isSelected()) {
            JOptionPane.showMessageDialog(this, "Korisnici su pretrazeni!");
        }
        if (jradioProstorija.isSelected()) {
            JOptionPane.showMessageDialog(this, "Prostorije su pretrazeni!");
        }
    }//GEN-LAST:event_jbtnTraziActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnResetujRezultate;
    private javax.swing.JButton jbtnTrazi;
    private javax.swing.JButton jbtn_detalji;
    private javax.swing.JRadioButton jradioBrojRezervacije;
    private javax.swing.JRadioButton jradioDatumRezervacije;
    private javax.swing.JRadioButton jradioKorisnik;
    private javax.swing.JRadioButton jradioProstorija;
    private javax.swing.JRadioButton jradioVremeDo;
    private javax.swing.JRadioButton jradioVremeOd;
    private javax.swing.JTable jtblRezervacije;
    private javax.swing.JTextField jtxtPretraga;
    // End of variables declaration//GEN-END:variables

    private void popuniComboKorisnici() {
//        jComboKorisnici.removeAllItems();
//        List<Korisnik> listaKorisnika = new ArrayList<>();
//        try {
//            listaKorisnika = Kontroler.vratiInstancuKontrolera().vratiListuKorisnika();
//        } catch (SQLException ex) {
//            System.out.println("Korisnici nisu pronadjeni!");
//        }
//        for (Korisnik korisnik : listaKorisnika) {
//            jComboKorisnici.addItem(korisnik);
//        }
    }

    private void popuniTabeluKorisnici() {
        List<Korisnik> lk = new ArrayList<>();
        try {
            lk = Kontroler.vratiInstancuKontrolera().vratiListuKorisnika();
        } catch (Exception ex) {
            System.out.println("Korisnici nisu pronadjeni!");
        }
        jtblRezervacije.setModel(new TblModelKorisnik(lk));

        ListSelectionModel lsm = jtblRezervacije.getSelectionModel();
        lsm.setSelectionInterval(0, 0);
    }

    private void dodajComboMestaUTabelu() {
        JComboBox jck = new JComboBox<Mesto>();
        try {
            jck.setModel(new DefaultComboBoxModel(Kontroler.vratiInstancuKontrolera().vratiListuMesta().toArray()));
        } catch (Exception ex) {
            System.out.println("Mesta nisu pronadjena!");
        }

        TableColumnModel tcm = jtblRezervacije.getColumnModel();
        TableColumn tm = tcm.getColumn(5);
        tm.setCellEditor(new DefaultCellEditor(jck));
    }

    private void srediTabelu() {
        
        List<Rezervacija> lr = new ArrayList<>();
        try {
            lr = Kontroler.vratiInstancuKontrolera().vratiListuRezervacija();
        } catch (Exception ex) {
            System.out.println("Korisnici nisu pronadjeni!");
        }
        jtblRezervacije.setModel(new TblModelRezervacija(lr));
        
    }

}
